# Generated by Django 5.2 on 2025-04-06 05:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_items_itmesloan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.department'),
        ),
        migrations.CreateModel(
            name='ItemsLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=100)),
                ('borrower_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('loan_date', models.DateField(default=django.utils.timezone.now)),
                ('return_date', models.DateField()),
                ('status', models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('in_stock', 'In_stock')], default='in_stock', max_length=20)),
                ('returned_on', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemloans', to='inventory.items')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
            },
        ),
        migrations.DeleteModel(
            name='ItmesLoan',
        ),
    ]
