# Generated by Django 5.2 on 2025-04-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_items_department_itemsloan_delete_itmesloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsloan',
            name='borrow_qty',
            field=models.IntegerField(default=1),
        ),
    ]
